services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    user: node
    ports:
      - 3000:3000
    volumes:
      - ./:/workspace/
      - node_modules:/workspace/my-app/node_modules
    # 以下必要に応じて変更
    tty: true
volumes:
  node_modules: