services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    user: node
    volumes:
      - ../:/workspace/
      # - node_modules:/workspace/test/node_modules
    # 以下必要に応じて変更
    tty: true
volumes:
  node_modules: